---
# file: .travis.yml

language: python

python:
  - "2.7"
  - "3.6"

services: docker

install:
  - pip install testinfra molecule docker

script:
  - molecule --version
  - ansible --version
  - molecule test -s all
