---
# role: ansible-role-ca
# file: tasks/create.yml

- name: debug
  debug:
    msg: "{{ ca_certs }}"

- name: Set fact for list of certificates to create
  set_fact:
    ca_certificates: |
      {% set ca_cert_list = [] -%}
      {% for ca_cert_key in ca_certs.keys() -%}
        {% for ca_config_key in ca_certs[ca_cert_key].keys() -%}
          {% for ca_cert in ca_certs[ca_cert_key][ca_config_key] -%}
            {% set ca_dummy = ca_cert_list.extend(
                 [{ 'ca': ca_cert_key,
                    'cn': ca_cert.cn,
                    'config': ca_config_key,
                    'email': ca_cert.email | default ('', True),
                    'file': ca_cert.cn | replace(' ', '-') | regex_replace('[\(\)]') | regex_replace('^CN=(.*)-OU=.*$','\\1') | lower,
                    'exports': ca_cert.export | default([], True),
                    'protect_key': ca_cert.protect_key | default(False, True),
                    'san': ca_cert.san | default([], True) }]
               ) -%}
          {%- endfor %}
        {%- endfor %}
      {%- endfor %}
      {{ ca_cert_list }}

- name: Create configuration files
  template:
    src: "etc/{{ item.config }}.conf.j2"
    dest: "{{ ca_base_dir }}/etc/{{ item.file }}.conf"
    owner: root
    group: root
    mode: '600'
  loop: "{{ ca_certificates }}"

- name: Create CSRs
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca -r {{ item.file }} {{ item.protect_key | ternary('-p','') }}
  args:
    chdir: "{{ ca_base_dir }}/"
    creates: "{{ ca_base_dir }}/csr/{{ item.file }}.csr"
  loop: "{{ ca_certificates }}"

- name: Issue certificates
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca \
      -i {{ item.file }} \
      -e {{ item.config }} \
      -s {{ item.ca }}
  args:
    chdir: "{{ ca_base_dir }}/"
    creates: "{{ ca_base_dir }}/certs/{{ item.file }}.crt"
  loop: "{{ ca_certificates }}"

# - name: Debug ca_certificates
#   debug:
#     msg: "{{ item }}"
#   loop: "{{ ca_certificates }}"

- name: Set fact for export list
  set_fact:
    ca_exports: |
      {%- set ca_export_list = [] -%}
      {%- for ca_cert_item in ca_certificates -%}
        {%- for ca_export_item in ca_cert_item.exports -%}
          {%- set ca_dummy = ca_export_list.extend(
            [{
              'ca': ca_cert_item.ca,
              'cn': ca_cert_item.cn,
              'config': ca_cert_item.config,
              'export': ca_export_item,
              'file': ca_cert_item.file,
              'protect_key': ca_cert_item.protect_key
            }]) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ ca_export_list }}

# - name: Convert Certificates to specified formats
#   debug:
#     msg: "{{ item }}"
#   loop: "{{ ca_exports }}"

- name: Issue certificates
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca \
      -t {{ item.file | quote }} \
      -f {{ item.export | quote }} \
      -s {{ item.ca | quote }} \
      -u {{ item.cn | quote }} \
      {{ item.protect_key | ternary('-p', '') }}
  args:
    chdir: "{{ ca_base_dir }}/"
    creates: "{{ ca_base_dir }}/certs/{{ item.file }}.{{ item.export | lower }}"
  loop: "{{ ca_exports }}"
