---
# role: ansible-role-ca
# file: tasks/create.yml

- name: Set fact for list of certificates to create
  set_fact:
    ca_certificate_dict: |
      {% set cert_dict = [] -%}
      {% for ca in ca_certs.keys() -%}
        {% for config in ca_certs[ca].keys() -%}
          {% for cert in ca_certs[ca][config] -%}
            {% set ca_dummy = cert_dict.extend(
                 [{ 'ca': ca,
                    'config': config,
                    'cert': cert,
                    'file': cert.cn | replace(' ', '-') | regex_replace('[\(\)]') | regex_replace('^CN=(.*)-OU=.*$','\\1') | lower }]
               ) -%}
          {%- endfor %}
        {%- endfor %}
      {%- endfor %}
      {{ cert_dict }}

- name: Create CSR configuration files
  template:
    src: "etc/{{ item.config }}.conf.j2"
    dest: "{{ ca_base_dir }}/etc/{{ item.file }}.conf"
    owner: root
    group: root
    mode: '600'
  loop: "{{ ca_certificate_dict }}"

- name: Create certificates
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca-create-{{ item.config }} \
      {{ item.file }} \
      {{ item.config }} \
      {{ item.ca }}
  args:
    chdir: "{{ ca_base_dir }}/"
    creates: "{{ ca_base_dir }}/certs/{{ item.file }}.pem"
    executable: '/bin/sh'
  loop: "{{ ca_certificate_dict }}"
