---
# role: ansible-role-ca
# file: tasks/main.yml

- name: "Tasks for ansible-role-ca"
  block:
    - name: "Install packages for ansible-role-ca"
      package:
        name: "{{ ca_packages }}"
        state: present
  when: ca_role_enabled | bool
