---
# role: ansible-role-ca
# file: tasks/main.yml

- name: "Tasks for ansible-role-ca"
  block:
    - name: "Install packages for ansible-role-ca"
      package:
        name: "{{ ca_packages }}"
        state: present
    - name: "Initialiize CAs"
      myca_init:
        cainfo: "{{ ca_info }}"
        calist: "{{ ca_list }}"
  when: ca_role_enabled | bool
