---
# role: ansible-role-ca
# file: tasks/revoke.yml

- name: Revoke certificates
  shell: |
    /usr/local/bin/{{ ca_name_short }}-ca-revoke \
      {{ item.file }} \
      {{ item.ca }}
  args:
    chdir: "/etc/ssl/{{ ca_name_short }}/"
    removes: "/etc/ssl/{{ ca_name_short }}/certs/{{ item.file }}.pem"
    executable: '/bin/sh'
  loop: "{{ ca_revoke }}"
  notify: Regenerate CRLs
