---
# role: ansible-role-ca
# file: tasks/revoke.yml

- name: Revoke certificates
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca-revoke \
      {{ item.file }} \
      {{ item.ca }}
  args:
    chdir: "{{ ca_base_dir }}/"
    removes: "{{ ca_base_dir }}/certs/{{ item.file }}.pem"
    executable: '/bin/sh'
  loop: "{{ ca_revoke }}"
  notify: Regenerate CRLs
