---
# role: ansible-role-ca
# file: handlers/main.yml

- name: Update trusted CA certs
  command: "{{ ca_trusted_update }}"

- name: Regenerate CRLs
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca -g
  args:
    removes: "{{ ca_base_dir }}/crl/root.ca.crl"
