---
# role: ansible-role-ca
# file: handlers/main.yml

- name: Update trusted CA certs
  command: "{{ ca_trusted_update }}"

- name: Regenerate CRLs
  shell: |
    /usr/local/bin/{{ ca_dir }}-ca-crl-root
    /usr/local/bin/{{ ca_dir }}-ca-crl-intermediate
    /usr/local/bin/{{ ca_dir }}-ca-crl-component
    /usr/local/bin/{{ ca_dir }}-ca-crl-identity
    /usr/local/bin/{{ ca_dir }}-ca-crl-software
  args:
    executable: '/bin/sh'
    removes: "{{ ca_base_dir }}/crl/root.ca.crl"
