---
# role: ansible-role-ca
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ca-default
    image: ${MOLECULE_DIST:-"jam82/ubuntu-molecule:18.04"}
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        ca_enabled: True
        ca_country: 'DE'
        ca_state: 'Bayern'
        ca_locality: 'Erlangen'
        ca_organization: 'Homebase'
        ca_organizational_unit: 'Homebase Certificate Authority'
        ca_name: 'Homebase'
        ca_dir: 'home'
        ca_base_url: 'http://pki.yourdomain.tld'
        ca_certs:
          component:
            client:
              - cn: 'My Mobile'
              - cn: 'My Tablet'
            mskdc:
              - cn: 'dc.yourdomain.tld'
                san:
                  - 'DNS = dc'
                  - 'DNS = ad.yourdomain.tld'
                  - 'IP = 192.168.10.10'
                  - 'otherName = 1.3.6.1.5.2.2;UTF8:dc.yourdomain.tld'
                  - 'otherName = 1.3.6.1.4.1.311.25.1;FORMAT:HEX,OCTETSTRING:2BEA00D953125447A22BCF28508DFED3'
            server:
              - cn: 'server.yourdomain.tld'
                san:
                  - 'DNS = server.yourdomain.tld'
                  - 'DNS = mail.yourdomain.tld'
                  - 'IP = 192.168.10.11'
            timestamp:
              - cn: 'My Software Timestamp'
            ocsp:
              - cn: 'My OCSP Signature'
          identity:
            email:
              - cn: 'Jonas Mauer (Mail)'
                email: 'jonas@yourdomain.tld'
                san:
                  - 'email:move'
                  - 'email:jam@yourdomain.tld'
                protect_key: True
            identity:
              - cn: 'Jonas Mauer (ID)'
                email: 'jonas@yourdomain.tld'
                san:
                  - 'email:move'
                  - 'otherName:1.3.6.1.4.1.311.20.2.3;UTF8:jonas@dc.yourdomain.tld'
                protect_key: True
          software:
            codesign:
              - cn: 'My Software'
                protect_key: True
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
