---
# role: ansible-role-ca
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 2048
      cpus: 2
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: arch-ca
    box: "archlinux/archlinux"
  - name: centos-ca
    box: "centos/8"
  - name: debian-ca
    box: "debian/bullseye64"
  - name: fedora-ca
    box: "fedora/33-cloud-base"
  - name: opensuse-ca
    box: "generic/opensuse15"
  - name: oracle-ca
    box: "generic/oracle8"
  - name: ubuntu-ca
    box: "generic/ubuntu2004"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        ca_role_enabled: true
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: true
    sudo: true
